### ISSUE TITLE
Katas 1: Get multiple array value

### ISSUE THREAD

**Issue by udarakalpana** [udarakalpana/javascript_katas#4]
Given an array of numbers, return a new array where each number is multiply by 2.

// Given array
const numbers = [1, 5, 10, 100, 45, 36]

//Output should want to this when console.log new returning numbers
[2, 10, 20, 200, 95, 72 ]

**Comment by TharinduUdara** [comment]
@udarakalpana i started

**Comment by SKNC-KARUNANAYAKA** [comment]
@udarakalpana I start Katas 1(Get multiple array value)
